sudo: required
services: docker

script:
    - docker pull fdietze/docker-alpine-scala-webdev:latest
    - docker build . --cache-from fdietze/docker-alpine-scala-webdev:latest -t fdietze/docker-alpine-scala-webdev:latest
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push fdietze/docker-alpine-scala-webdev:latest
