sudo: required
services: docker

script:
    - docker pull fdietze/docker-alpine-scala-webdev:latest
    - docker build . --cache-from fdietze/docker-alpine-scala-webdev:latest -t fdietze/docker-alpine-scala-webdev:latest -t fdietze/docker-alpine-scala-webdev:"$TRAVIS_COMMIT"
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    - docker push fdietze/docker-alpine-scala-webdev:"$TRAVIS_COMMIT"
    - docker push fdietze/docker-alpine-scala-webdev:latest
